import re

from fastapi import HTTPException, status
from pydantic import ValidationError

from app.core.llm_client import BaseLLMClient
from app.models.resume_schema import ResumeProfile


_SUMMARY_HEADING_RE = re.compile(
    r"^\s*(?:profile\s+summary|professional\s+summary|summary|profile)\s*[:\n]+",
    flags=re.IGNORECASE,
)
_LINE_ITEM_DELIMITER_RE = re.compile(
    r"(?m)(?:^|\n)\s*(?:[-*•◦▪▫‣⁃∙●○■□◆◇❖➢➤✓✔]|\d+[.)])\s+"
)
_INLINE_GRAPHIC_DELIMITER_RE = re.compile(r"\s*[•◦▪▫‣⁃∙●○■□◆◇❖➢➤✓✔]\s+")
_INLINE_HYPHEN_DELIMITER_RE = re.compile(r"\s+-\s+(?=[A-Z0-9])")
_WHITESPACE_RE = re.compile(r"\s+")
_TRAILING_FIELD_OF_STUDY_RE = re.compile(r"^(?P<degree>.+?)\s*\((?P<field>[^()]+)\)\s*$")
_SKILL_SPLIT_RE = re.compile(r"(?:\r?\n|[;,]|\s+\|\s+)")
_SKILL_BULLET_PREFIX_RE = re.compile(r"^\s*(?:[-*]|\d+[.)])\s+")
_SKILL_LABEL_PREFIX_RE = re.compile(
    r"(?i)^\s*(?:technical\s+skills|skills|core\s+competencies|competencies|"
    r"programming\s+languages|languages|frameworks|libraries|tools|technologies|"
    r"databases|cloud|methodologies)\s*:\s*"
)
_SKILL_AI_GENERATED_KEYS = (
    "aiGenerated",
    "ai_generated",
    "isAiGenerated",
    "is_ai_generated",
    "generatedByAi",
    "aiSuggested",
    "suggested",
)
_AI_GENERATED_TRUE_VALUES = {
    "true",
    "1",
    "yes",
    "y",
    "ai",
    "ai generated",
    "ai-generated",
    "ai suggested",
    "ai-suggested",
    "generated",
    "generated by ai",
    "suggested",
    "job description",
    "jd",
}
_AI_GENERATED_FALSE_VALUES = {
    "",
    "false",
    "0",
    "no",
    "n",
    "resume",
    "resume extracted",
    "resume-extracted",
    "extracted",
    "not ai generated",
}
_FIELD_OF_STUDY_KEYS = ("fieldOfStudy", "field_of_study", "field", "major", "specialization", "specialisation")
_NON_FIELD_OF_STUDY_MARKERS = {
    "hon",
    "hons",
    "honor",
    "honors",
    "honour",
    "honours",
    "with honors",
    "with honours",
    "distinction",
    "merit",
}


def _normalize_summary_item_text(value: str) -> str:
    return _WHITESPACE_RE.sub(" ", value).strip(" \t\r\n-*:;")


def _clean_optional_text(value: object) -> str:
    if value is None:
        return ""
    return _WHITESPACE_RE.sub(" ", str(value)).strip(" \t\r\n-*:;")


def split_summary_items(value: str) -> list[str]:
    text = _SUMMARY_HEADING_RE.sub("", value.strip(), count=1)
    if not text:
        return []

    parts = [part for part in _LINE_ITEM_DELIMITER_RE.split(text) if part.strip()]
    if len(parts) <= 1:
        parts = [part for part in _INLINE_GRAPHIC_DELIMITER_RE.split(text) if part.strip()]
    if len(parts) <= 1 and text.lstrip().startswith("- "):
        parts = [part for part in _INLINE_HYPHEN_DELIMITER_RE.split(text) if part.strip()]

    return [normalized for part in parts if (normalized := _normalize_summary_item_text(part))]


def normalize_summary_section_items(raw_profile: dict) -> None:
    data = raw_profile.get("data")
    if not isinstance(data, dict):
        return

    sections = data.get("sections")
    if not isinstance(sections, list):
        return

    for section in sections:
        if not isinstance(section, dict):
            continue

        section_type = section.get("type")
        if not isinstance(section_type, str) or section_type.strip().lower() != "summary":
            continue

        items = section.get("items")
        if isinstance(items, str):
            summary_items = split_summary_items(items)
            if len(summary_items) > 1:
                section["items"] = summary_items
            continue

        if isinstance(items, list):
            summary_items: list[object] = []
            changed = False
            for item in items:
                if not isinstance(item, str):
                    summary_items.append(item)
                    continue

                split_items = split_summary_items(item)
                if len(split_items) > 1:
                    summary_items.extend(split_items)
                    changed = True
                elif split_items:
                    summary_items.append(split_items[0])
                else:
                    changed = True

            if changed:
                section["items"] = summary_items


def _split_degree_field_of_study(degree: str) -> tuple[str, str]:
    match = _TRAILING_FIELD_OF_STUDY_RE.fullmatch(degree.strip())
    if not match:
        return degree, ""

    parsed_degree = _clean_optional_text(match.group("degree"))
    parsed_field = _clean_optional_text(match.group("field"))
    if not parsed_degree or not parsed_field:
        return degree, ""

    marker = parsed_field.lower().strip(".")
    if marker in _NON_FIELD_OF_STUDY_MARKERS:
        return degree, ""

    return parsed_degree, parsed_field


def normalize_education_field_of_study(raw_profile: dict) -> None:
    data = raw_profile.get("data")
    if not isinstance(data, dict):
        return

    sections = data.get("sections")
    if not isinstance(sections, list):
        return

    for section in sections:
        if not isinstance(section, dict):
            continue

        section_type = section.get("type")
        if not isinstance(section_type, str) or section_type.strip().lower() != "education":
            continue

        items = section.get("items")
        if not isinstance(items, list):
            continue

        for item in items:
            if not isinstance(item, dict):
                continue

            field_of_study = ""
            for key in _FIELD_OF_STUDY_KEYS:
                if key not in item:
                    continue
                value = _clean_optional_text(item.get(key))
                if value and not field_of_study:
                    field_of_study = value
                if key != "fieldOfStudy":
                    item.pop(key, None)

            degree = _clean_optional_text(item.get("degree"))
            if degree:
                parsed_degree, parsed_field = _split_degree_field_of_study(degree)
                if parsed_field:
                    item["degree"] = parsed_degree
                    if not field_of_study:
                        field_of_study = parsed_field

            if field_of_study:
                item["fieldOfStudy"] = field_of_study


def _split_skill_names(value: object) -> list[str]:
    text = _SKILL_LABEL_PREFIX_RE.sub("", _clean_optional_text(value))
    if not text:
        return []

    names: list[str] = []
    for part in _SKILL_SPLIT_RE.split(text):
        name = _SKILL_LABEL_PREFIX_RE.sub("", _SKILL_BULLET_PREFIX_RE.sub("", _clean_optional_text(part)))
        if name:
            names.append(name)
    return names


def _normalize_ai_generated_flag(value: object) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    if isinstance(value, (int, float)):
        return bool(value)

    text = _clean_optional_text(value).casefold()
    if text in _AI_GENERATED_TRUE_VALUES:
        return True
    if text in _AI_GENERATED_FALSE_VALUES:
        return False
    return False


def _skill_ai_generated_from_raw_item(raw_item: dict) -> bool:
    for key in _SKILL_AI_GENERATED_KEYS:
        if key in raw_item:
            return _normalize_ai_generated_flag(raw_item.get(key))

    source = _clean_optional_text(raw_item.get("source") or raw_item.get("origin")).casefold()
    if source in {
        "ai",
        "ai generated",
        "ai-generated",
        "ai suggested",
        "ai-suggested",
        "generated",
        "generated by ai",
        "suggested",
        "job description",
        "target job description",
        "jd",
        "llm",
    }:
        return True
    if source in {"resume", "resume extracted", "resume-extracted", "extracted", "parsed"}:
        return False
    return False


def _append_skill_item(
    items: list[dict[str, object]],
    seen: dict[str, int],
    name: str,
    ai_generated: bool = False,
) -> None:
    key = name.casefold()
    if key in seen:
        index = seen[key]
        if not ai_generated and items[index].get("aiGenerated"):
            items[index]["aiGenerated"] = False
        return

    seen[key] = len(items)
    items.append({"name": name, "aiGenerated": ai_generated})


def normalize_skill_section_items(raw_profile: dict) -> None:
    data = raw_profile.get("data")
    if not isinstance(data, dict):
        return

    sections = data.get("sections")
    if not isinstance(sections, list):
        return

    for section in sections:
        if not isinstance(section, dict):
            continue

        section_type = section.get("type")
        if not isinstance(section_type, str) or section_type.strip().lower() != "skill":
            continue

        raw_items = section.get("items")
        normalized_items: list[dict[str, object]] = []
        seen: dict[str, int] = {}

        if isinstance(raw_items, str):
            for name in _split_skill_names(raw_items):
                _append_skill_item(normalized_items, seen, name)
        elif isinstance(raw_items, list):
            for raw_item in raw_items:
                if isinstance(raw_item, str):
                    for name in _split_skill_names(raw_item):
                        _append_skill_item(normalized_items, seen, name)
                    continue

                if not isinstance(raw_item, dict):
                    continue

                name = _clean_optional_text(
                    raw_item.get("name")
                    or raw_item.get("skill")
                    or raw_item.get("technology")
                    or raw_item.get("tool")
                )
                ai_generated = _skill_ai_generated_from_raw_item(raw_item)
                if not name:
                    continue

                split_names = _split_skill_names(name)
                if len(split_names) > 1:
                    for split_name in split_names:
                        _append_skill_item(normalized_items, seen, split_name, ai_generated)
                    continue

                _append_skill_item(normalized_items, seen, split_names[0] if split_names else name, ai_generated)

        if normalized_items:
            section["items"] = normalized_items


def normalize_resume_profile_payload(raw_profile: object) -> object:
    if not isinstance(raw_profile, dict):
        return raw_profile

    wrapped_profile = raw_profile.get("profile")
    if isinstance(wrapped_profile, dict):
        normalize_summary_section_items(wrapped_profile)
        normalize_education_field_of_study(wrapped_profile)
        normalize_skill_section_items(wrapped_profile)
        return wrapped_profile

    normalize_summary_section_items(raw_profile)
    normalize_education_field_of_study(raw_profile)
    normalize_skill_section_items(raw_profile)
    return raw_profile


class ResumeParserService:
    def __init__(self, llm_client: BaseLLMClient):
        self.llm_client = llm_client

    async def parse(self, resume_text: str, job_description: str | None) -> ResumeProfile:
        raw_profile = await self.llm_client.extract_resume_profile(resume_text, job_description)
        raw_profile = normalize_resume_profile_payload(raw_profile)
        try:
            return ResumeProfile.model_validate(raw_profile)
        except ValidationError as exc:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail={
                    "message": "LLM response did not match the resume schema.",
                    "errors": exc.errors(),
                },
            ) from exc
