import re
from datetime import date, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


def normalize_optional_string(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return str(value)


def normalize_boolean_flag(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    if isinstance(value, (int, float)):
        return bool(value)

    text = str(value).strip().casefold()
    if text in {
        "true",
        "1",
        "yes",
        "y",
        "ai",
        "ai generated",
        "ai-generated",
        "ai suggested",
        "ai-suggested",
        "generated",
        "generated by ai",
        "suggested",
        "job description",
        "jd",
    }:
        return True
    if text in {
        "",
        "false",
        "0",
        "no",
        "n",
        "resume",
        "resume extracted",
        "resume-extracted",
        "extracted",
        "not ai generated",
    }:
        return False
    return False


_MONTH_NUMBERS = {
    "jan": 1,
    "january": 1,
    "feb": 2,
    "february": 2,
    "mar": 3,
    "march": 3,
    "apr": 4,
    "april": 4,
    "may": 5,
    "jun": 6,
    "june": 6,
    "jul": 7,
    "july": 7,
    "aug": 8,
    "august": 8,
    "sep": 9,
    "sept": 9,
    "september": 9,
    "oct": 10,
    "october": 10,
    "nov": 11,
    "november": 11,
    "dec": 12,
    "december": 12,
}
_MONTH_PATTERN = "|".join(sorted(_MONTH_NUMBERS, key=len, reverse=True))
_CURRENT_ROLE_VALUES = {"present", "current", "currently", "now", "ongoing", "to date", "till date"}


def _expand_year(value: str) -> int | None:
    year_text = value.strip().lstrip("'")
    if not year_text.isdigit():
        return None

    if len(year_text) == 2:
        year = int(year_text)
        return 1900 + year if year >= 70 else 2000 + year
    if len(year_text) == 4:
        return int(year_text)
    return None


def _format_date(day: int, month: int, year: int) -> str | None:
    if year < 1900 or year > 2100:
        return None
    try:
        date(year, month, day)
        return f"{day:02d}-{month:02d}-{year:04d}" if day and month else None
    except ValueError:
        return None


def _valid_date(day: int, month: int, year: int) -> str | None:
    if month < 1 or month > 12:
        return None
    if day < 1 or day > 31:
        return None
    return _format_date(day, month, year)


def normalize_work_experience_date(value: Any) -> str:
    text = normalize_optional_string(value).strip()
    if not text:
        return ""

    compact = re.sub(r"\s+", " ", text).strip()
    if compact.strip(" .").lower() in _CURRENT_ROLE_VALUES:
        return "Present"

    normalized = re.sub(r"\b(\d{1,2})(?:st|nd|rd|th)\b", r"\1", compact, flags=re.IGNORECASE)
    normalized = normalized.replace(",", " ").replace(".", " ")
    normalized = re.sub(r"\s+", " ", normalized).strip()

    match = re.fullmatch(r"(\d{4})[/-](\d{1,2})[/-](\d{1,2})", normalized)
    if match:
        year = _expand_year(match.group(1))
        if year is not None and (formatted := _valid_date(int(match.group(3)), int(match.group(2)), year)):
            return formatted

    match = re.fullmatch(r"(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})", normalized)
    if match:
        year = _expand_year(match.group(3))
        if year is not None and (formatted := _valid_date(int(match.group(1)), int(match.group(2)), year)):
            return formatted

    match = re.fullmatch(r"(\d{4})[/-](\d{1,2})", normalized)
    if match:
        year = _expand_year(match.group(1))
        if year is not None and (formatted := _valid_date(1, int(match.group(2)), year)):
            return formatted

    match = re.fullmatch(r"(\d{1,2})[/-](\d{2,4})", normalized)
    if match:
        year = _expand_year(match.group(2))
        if year is not None and (formatted := _valid_date(1, int(match.group(1)), year)):
            return formatted

    match = re.fullmatch(rf"(?i)({_MONTH_PATTERN})\s+(\d{{1,2}})\s+(\d{{2,4}})", normalized)
    if match:
        year = _expand_year(match.group(3))
        month = _MONTH_NUMBERS[match.group(1).lower()]
        if year is not None and (formatted := _valid_date(int(match.group(2)), month, year)):
            return formatted

    match = re.fullmatch(rf"(?i)(\d{{1,2}})\s+({_MONTH_PATTERN})\s+(\d{{2,4}})", normalized)
    if match:
        year = _expand_year(match.group(3))
        month = _MONTH_NUMBERS[match.group(2).lower()]
        if year is not None and (formatted := _valid_date(int(match.group(1)), month, year)):
            return formatted

    match = re.fullmatch(rf"(?i)({_MONTH_PATTERN})\s+(\d{{2,4}})", normalized)
    if match:
        year = _expand_year(match.group(2))
        month = _MONTH_NUMBERS[match.group(1).lower()]
        if year is not None and (formatted := _valid_date(1, month, year)):
            return formatted

    match = re.fullmatch(rf"(?i)(\d{{2,4}})\s+({_MONTH_PATTERN})", normalized)
    if match:
        year = _expand_year(match.group(1))
        month = _MONTH_NUMBERS[match.group(2).lower()]
        if year is not None and (formatted := _valid_date(1, month, year)):
            return formatted

    match = re.fullmatch(r"\d{2,4}", normalized)
    if match:
        year = _expand_year(normalized)
        if year is not None and (formatted := _valid_date(1, 1, year)):
            return formatted

    return compact


class StrictBaseModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class ExperienceSectionItem(StrictBaseModel):
    position: str = ""
    company: str = ""
    location: str = ""
    jobType: str = ""
    reasonForLeaving: str = ""
    start: str = ""
    end: str = ""
    achievements: list[str] = Field(default_factory=list)

    @field_validator("position", "company", "location", "jobType", "reasonForLeaving", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)

    @field_validator("start", "end", mode="before")
    @classmethod
    def normalize_dates(cls, value: Any) -> str:
        return normalize_work_experience_date(value)


class EducationSectionItem(StrictBaseModel):
    degree: str = ""
    fieldOfStudy: str = ""
    school: str = ""
    faculty: str = ""
    department: str = ""
    location: str = ""
    years: str = ""
    start: str = ""
    end: str = ""
    highlights: list[str] = Field(default_factory=list)

    @field_validator(
        "degree",
        "fieldOfStudy",
        "school",
        "faculty",
        "department",
        "location",
        "years",
        "start",
        "end",
        mode="before",
    )
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


class SkillSectionItem(StrictBaseModel):
    name: str = ""
    aiGenerated: bool = False

    @model_validator(mode="before")
    @classmethod
    def normalize_legacy_fields(cls, value: Any) -> Any:
        if not isinstance(value, dict):
            return value

        normalized = dict(value)
        normalized.pop("level", None)
        normalized.pop("proficiency", None)
        for key in (
            "ai_generated",
            "isAiGenerated",
            "is_ai_generated",
            "generatedByAi",
            "aiSuggested",
            "suggested",
        ):
            if "aiGenerated" not in normalized and key in normalized:
                normalized["aiGenerated"] = normalized[key]
            normalized.pop(key, None)
        return normalized

    @field_validator("name", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)

    @field_validator("aiGenerated", mode="before")
    @classmethod
    def normalize_ai_generated(cls, value: Any) -> bool:
        return normalize_boolean_flag(value)


class CourseSectionItem(StrictBaseModel):
    course: str = ""
    institution: str = ""
    start: str = ""
    end: str = ""

    @field_validator("course", "institution", "start", "end", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


class LanguageSectionItem(StrictBaseModel):
    language: str = ""
    level: str = ""

    @field_validator("language", "level", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


class ReferenceSectionItem(StrictBaseModel):
    name: str = ""
    company: str = ""
    email: str = ""
    phone: str = ""

    @field_validator("name", "company", "email", "phone", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


class LinkSectionItem(StrictBaseModel):
    label: str = ""
    link: str = ""

    @field_validator("label", "link", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


class InternshipSectionItem(StrictBaseModel):
    position: str = ""
    company: str = ""
    location: str = ""
    start: str = ""
    end: str = ""
    achievements: list[str] = Field(default_factory=list)

    @field_validator("position", "company", "location", "start", "end", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


SectionItem = (
    ExperienceSectionItem
    | EducationSectionItem
    | SkillSectionItem
    | CourseSectionItem
    | LanguageSectionItem
    | ReferenceSectionItem
    | LinkSectionItem
    | InternshipSectionItem
    | str
)


class ResumeSection(StrictBaseModel):
    title: str = ""
    type: str = ""
    items: str | list[SectionItem] = Field(default_factory=list)

    @field_validator("title", "type", mode="before")
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


class ResumeData(StrictBaseModel):
    name: str = ""
    title: str = ""
    location: str = ""
    phone: str = ""
    email: str = ""
    summary: str = ""
    dateOfBirth: str = ""
    gender: str = ""
    nationality: str = ""
    documentDate: str = ""
    address: str = ""
    postalCode: str = ""
    secondaryAddress: str | None = None
    sections: list[ResumeSection] = Field(default_factory=list)

    @field_validator(
        "name",
        "title",
        "location",
        "phone",
        "email",
        "summary",
        "dateOfBirth",
        "gender",
        "nationality",
        "documentDate",
        "address",
        "postalCode",
        mode="before",
    )
    @classmethod
    def normalize_strings(cls, value: Any) -> str:
        return normalize_optional_string(value)


class ResumeProfile(StrictBaseModel):
    data: ResumeData = Field(default_factory=ResumeData)


class ResumeParseResponse(StrictBaseModel):
    id: str
    profile: ResumeProfile
    metadata: dict[str, Any]
    resumeId: str | None = None
    userId: str | None = None
    version: int | None = None
    status: str | None = None
    avatar: str = ""
    withPhoto: bool = False
    atsScore: int | None = Field(default=None, ge=0, le=100)
    atsCalculation: dict[str, Any] | None = None
    atsCalculatedAt: datetime | None = None


class ResumeRephraseRequest(StrictBaseModel):
    text: str = Field(min_length=1, max_length=8000)
    prompt: str | None = Field(default=None, max_length=4000)

    @field_validator("text", "prompt", mode="before")
    @classmethod
    def normalize_text(cls, value: Any) -> str:
        return normalize_optional_string(value).strip()


class ResumeRephraseResponse(StrictBaseModel):
    rephrasedText: str = Field(min_length=1)

    @field_validator("rephrasedText", mode="before")
    @classmethod
    def normalize_rephrased_text(cls, value: Any) -> str:
        return normalize_optional_string(value).strip()
